//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.16 at 08:53:40 PM CEST 
//


package es.uned.master.enfoquegenerativo.xml.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for associationsComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="associationsComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oneOneDirect" type="{}oneOneDirectComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="manyManyInverse" type="{}manyManyInverseComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="oneOneInverse" type="{}oneOneInverseComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="oneMany" type="{}oneManyComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="manyOne" type="{}manyOneComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="manyManyDirect" type="{}manyManyDirectComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "associationsComplexType", propOrder = {
    "oneOneDirect",
    "manyManyInverse",
    "oneOneInverse",
    "oneMany",
    "manyOne",
    "manyManyDirect"
})
public class AssociationsComplexType {

    protected List<OneOneDirectComplexType> oneOneDirect;
    protected List<ManyManyInverseComplexType> manyManyInverse;
    protected List<OneOneInverseComplexType> oneOneInverse;
    protected List<OneManyComplexType> oneMany;
    protected List<ManyOneComplexType> manyOne;
    protected List<ManyManyDirectComplexType> manyManyDirect;

    /**
     * Gets the value of the oneOneDirect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oneOneDirect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOneOneDirect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OneOneDirectComplexType }
     * 
     * 
     */
    public List<OneOneDirectComplexType> getOneOneDirect() {
        if (oneOneDirect == null) {
            oneOneDirect = new ArrayList<OneOneDirectComplexType>();
        }
        return this.oneOneDirect;
    }

    /**
     * Gets the value of the manyManyInverse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manyManyInverse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManyManyInverse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManyManyInverseComplexType }
     * 
     * 
     */
    public List<ManyManyInverseComplexType> getManyManyInverse() {
        if (manyManyInverse == null) {
            manyManyInverse = new ArrayList<ManyManyInverseComplexType>();
        }
        return this.manyManyInverse;
    }

    /**
     * Gets the value of the oneOneInverse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oneOneInverse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOneOneInverse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OneOneInverseComplexType }
     * 
     * 
     */
    public List<OneOneInverseComplexType> getOneOneInverse() {
        if (oneOneInverse == null) {
            oneOneInverse = new ArrayList<OneOneInverseComplexType>();
        }
        return this.oneOneInverse;
    }

    /**
     * Gets the value of the oneMany property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oneMany property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOneMany().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OneManyComplexType }
     * 
     * 
     */
    public List<OneManyComplexType> getOneMany() {
        if (oneMany == null) {
            oneMany = new ArrayList<OneManyComplexType>();
        }
        return this.oneMany;
    }

    /**
     * Gets the value of the manyOne property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manyOne property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManyOne().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManyOneComplexType }
     * 
     * 
     */
    public List<ManyOneComplexType> getManyOne() {
        if (manyOne == null) {
            manyOne = new ArrayList<ManyOneComplexType>();
        }
        return this.manyOne;
    }

    /**
     * Gets the value of the manyManyDirect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manyManyDirect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManyManyDirect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManyManyDirectComplexType }
     * 
     * 
     */
    public List<ManyManyDirectComplexType> getManyManyDirect() {
        if (manyManyDirect == null) {
            manyManyDirect = new ArrayList<ManyManyDirectComplexType>();
        }
        return this.manyManyDirect;
    }

}
