//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.16 at 08:53:40 PM CEST 
//


package es.uned.master.enfoquegenerativo.xml.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for joinColumnComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="joinColumnComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="own" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="referenced" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "joinColumnComplexType")
public class JoinColumnComplexType {

    @XmlAttribute(name = "own")
    protected String own;
    @XmlAttribute(name = "referenced")
    protected String referenced;

    /**
     * Gets the value of the own property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwn() {
        return own;
    }

    /**
     * Sets the value of the own property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwn(String value) {
        this.own = value;
    }

    /**
     * Gets the value of the referenced property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenced() {
        return referenced;
    }

    /**
     * Sets the value of the referenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenced(String value) {
        this.referenced = value;
    }

}
