//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.16 at 08:53:40 PM CEST 
//


package es.uned.master.enfoquegenerativo.xml.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.uned.master.enfoquegenerativo.xml.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.uned.master.enfoquegenerativo.xml.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Jpa }
     * 
     */
    public Jpa createJpa() {
        return new Jpa();
    }

    /**
     * Create an instance of {@link DomainObjectComplexType }
     * 
     */
    public DomainObjectComplexType createDomainObjectComplexType() {
        return new DomainObjectComplexType();
    }

    /**
     * Create an instance of {@link OneOneInverseComplexType }
     * 
     */
    public OneOneInverseComplexType createOneOneInverseComplexType() {
        return new OneOneInverseComplexType();
    }

    /**
     * Create an instance of {@link TableComplexType }
     * 
     */
    public TableComplexType createTableComplexType() {
        return new TableComplexType();
    }

    /**
     * Create an instance of {@link OneOneDirectComplexType }
     * 
     */
    public OneOneDirectComplexType createOneOneDirectComplexType() {
        return new OneOneDirectComplexType();
    }

    /**
     * Create an instance of {@link CascadeComplexType }
     * 
     */
    public CascadeComplexType createCascadeComplexType() {
        return new CascadeComplexType();
    }

    /**
     * Create an instance of {@link JoinColumnsComplexType }
     * 
     */
    public JoinColumnsComplexType createJoinColumnsComplexType() {
        return new JoinColumnsComplexType();
    }

    /**
     * Create an instance of {@link ManyOneComplexType }
     * 
     */
    public ManyOneComplexType createManyOneComplexType() {
        return new ManyOneComplexType();
    }

    /**
     * Create an instance of {@link AssociationsComplexType }
     * 
     */
    public AssociationsComplexType createAssociationsComplexType() {
        return new AssociationsComplexType();
    }

    /**
     * Create an instance of {@link RepositoryComplexType }
     * 
     */
    public RepositoryComplexType createRepositoryComplexType() {
        return new RepositoryComplexType();
    }

    /**
     * Create an instance of {@link SearchMethodsComplexType }
     * 
     */
    public SearchMethodsComplexType createSearchMethodsComplexType() {
        return new SearchMethodsComplexType();
    }

    /**
     * Create an instance of {@link ManyManyInverseComplexType }
     * 
     */
    public ManyManyInverseComplexType createManyManyInverseComplexType() {
        return new ManyManyInverseComplexType();
    }

    /**
     * Create an instance of {@link EntityComplexType }
     * 
     */
    public EntityComplexType createEntityComplexType() {
        return new EntityComplexType();
    }

    /**
     * Create an instance of {@link SearchMethodComplexType }
     * 
     */
    public SearchMethodComplexType createSearchMethodComplexType() {
        return new SearchMethodComplexType();
    }

    /**
     * Create an instance of {@link ManyManyDirectComplexType }
     * 
     */
    public ManyManyDirectComplexType createManyManyDirectComplexType() {
        return new ManyManyDirectComplexType();
    }

    /**
     * Create an instance of {@link FieldComplexType }
     * 
     */
    public FieldComplexType createFieldComplexType() {
        return new FieldComplexType();
    }

    /**
     * Create an instance of {@link OneManyComplexType }
     * 
     */
    public OneManyComplexType createOneManyComplexType() {
        return new OneManyComplexType();
    }

    /**
     * Create an instance of {@link FieldsComplexType }
     * 
     */
    public FieldsComplexType createFieldsComplexType() {
        return new FieldsComplexType();
    }

    /**
     * Create an instance of {@link JoinTableComplexType }
     * 
     */
    public JoinTableComplexType createJoinTableComplexType() {
        return new JoinTableComplexType();
    }

    /**
     * Create an instance of {@link JoinColumnComplexType }
     * 
     */
    public JoinColumnComplexType createJoinColumnComplexType() {
        return new JoinColumnComplexType();
    }

}
