//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.16 at 08:53:40 PM CEST 
//


package es.uned.master.enfoquegenerativo.xml.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oneManyComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oneManyComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cascade" type="{}cascadeComplexType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="referencedProperty" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relatedEntity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retrievingMode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oneManyComplexType", propOrder = {
    "cascade"
})
public class OneManyComplexType {

    protected CascadeComplexType cascade;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "referencedProperty")
    protected String referencedProperty;
    @XmlAttribute(name = "relatedEntity")
    protected String relatedEntity;
    @XmlAttribute(name = "retrievingMode")
    protected String retrievingMode;

    /**
     * Gets the value of the cascade property.
     * 
     * @return
     *     possible object is
     *     {@link CascadeComplexType }
     *     
     */
    public CascadeComplexType getCascade() {
        return cascade;
    }

    /**
     * Sets the value of the cascade property.
     * 
     * @param value
     *     allowed object is
     *     {@link CascadeComplexType }
     *     
     */
    public void setCascade(CascadeComplexType value) {
        this.cascade = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the referencedProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedProperty() {
        return referencedProperty;
    }

    /**
     * Sets the value of the referencedProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedProperty(String value) {
        this.referencedProperty = value;
    }

    /**
     * Gets the value of the relatedEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedEntity() {
        return relatedEntity;
    }

    /**
     * Sets the value of the relatedEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedEntity(String value) {
        this.relatedEntity = value;
    }

    /**
     * Gets the value of the retrievingMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetrievingMode() {
        return retrievingMode;
    }

    /**
     * Sets the value of the retrievingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetrievingMode(String value) {
        this.retrievingMode = value;
    }

}
